# Generated by Django 2.0.6 on 2018-06-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Jogadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('posicao', models.CharField(choices=[('GL', 'Goleiro'), ('ZA', 'Zagueiro'), ('LT', 'Lateral'), ('MC', 'Meio Campo'), ('AT', 'Atacante')], max_length=15)),
                ('cartoes_amarelos', models.IntegerField()),
                ('cartao_vermelho', models.IntegerField()),
                ('gols', models.IntegerField()),
                ('nacionalidade', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Partidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('gols_marcados', models.IntegerField()),
                ('gols_sofridos', models.IntegerField()),
                ('vitorias', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('status', models.CharField(choices=[('ELIMINADO', 'Eliminado'), ('COMPETINDO', 'Competindo'), ('CAMPEAO', 'Campeão')], max_length=15)),
                ('competicao', models.CharField(max_length=70)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Jogadores')),
            ],
        ),
        migrations.AddField(
            model_name='partidas',
            name='adversarioA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Time'),
        ),
        migrations.AddField(
            model_name='grupos',
            name='time',
            field=models.ManyToManyField(to='api.Time'),
        ),
    ]
