# Generated by Django 2.0.6 on 2018-06-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogadores',
            name='cartao_vermelho',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jogadores',
            name='cartoes_amarelos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jogadores',
            name='gols',
            field=models.IntegerField(null=True),
        ),
    ]
